# Generated by Django 3.2.5 on 2021-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datamaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('arab', models.TextField(max_length=1000)),
                ('indonesia', models.TextField(max_length=1000)),
                ('perawi', models.CharField(max_length=60)),
            ],
        ),
    ]
