# Generated by Django 3.2.5 on 2021-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doa', models.CharField(max_length=100)),
                ('arab', models.TextField(max_length=1000)),
                ('indonesia', models.TextField(max_length=1000)),
            ],
        ),
    ]
